name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa à meia-noite UTC diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: SavioHolandaQA
          svg_out_path: assets/github-contribution-grid-snake.svg

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/github-contribution-grid-snake.svg
          git commit -m "Update snake visualization"
          git push
